variable "cidr" {}
variable "env" {}
variable "web_subnets" {}
variable "app_subnets" {}
variable "db_subnets" {}
variable "public_subnets" {}
variable "availability_zones" {}
variable "default_vpc_id" {}
variable "default_vpc_rt" {}
variable "default_vpc_cidr" {}